# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef456c35d8095277c1c075e665ff338a627fe589528fd42f95ae04c3e82c1b5df71abd82d7b783ac05ed3c45f9ea5bfa62bbc5812ee6132353e129488fe8c24

test:
  secret_key_base: 711e557d8c581a82411a507b91c2c00d4f044f19c26f0c3985bbb20e693ea5083b5a873d0abca710b21035c61f9dba98e49aa504977ccf2d7893b958d377b382

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
